#!/usr/bin/env node
// MCP(Gmail) 셋업 — .env(단일 소스)에서 .pi/mcp.json 생성 + deps 설치 + 자작 서버 인증.
// 사용:  cp .env.example .env   (값 채우기)   →   node mcp-servers/setup.mjs
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const ENV_PATH = join(ROOT, ".env");
const PI_MCP = join(ROOT, ".pi", "mcp.json");
const GMAIL_DIR = join(HERE, "gmail-send");
const TOKEN = join(GMAIL_DIR, ".token.json");

// 간단한 .env 파서 (KEY=VALUE, #주석, 따옴표·export 허용)
function parseEnv(p) {
  const out = {};
  if (!existsSync(p)) return out;
  for (let line of readFileSync(p, "utf8").split("\n")) {
    line = line.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("export ")) line = line.slice(7);
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
    out[key] = val;
  }
  return out;
}

const env = parseEnv(ENV_PATH);
const clientId = env.GMAIL_OAUTH_CLIENT_ID;
const clientSecret = env.GMAIL_OAUTH_CLIENT_SECRET;

if (!clientId || !clientSecret) {
  console.error("✗ .env 에 GMAIL_OAUTH_CLIENT_ID / GMAIL_OAUTH_CLIENT_SECRET 가 필요합니다.");
  console.error("  먼저:  cp .env.example .env   후 값 채우기");
  process.exit(1);
}

// 1) .pi/mcp.json 생성 (.env → 설정. 손수정 금지, .env 고치고 재실행)
mkdirSync(dirname(PI_MCP), { recursive: true });
const config = {
  _generated: "AUTO-GENERATED by mcp-servers/setup.mjs from .env — 직접 수정하지 마세요. .env를 고치고 이 스크립트를 다시 실행하세요.",
  mcpServers: {
    gmail: {
      url: "https://gmailmcp.googleapis.com/mcp/v1",
      auth: "oauth",
      oauth: {
        clientId,
        clientSecret,
        redirectUri: "http://localhost:3118/callback",
        scope: "https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.compose",
      },
    },
    "gmail-send": { command: "node", args: ["./mcp-servers/gmail-send/index.mjs"] },
  },
};
writeFileSync(PI_MCP, JSON.stringify(config, null, 2) + "\n");
console.log("✓ .pi/mcp.json 생성 (gmail + gmail-send)");

// 2) 자작 서버 의존성
if (!existsSync(join(GMAIL_DIR, "node_modules"))) {
  console.log("• gmail-send 의존성 설치 중…");
  execFileSync("npm", ["install"], { cwd: GMAIL_DIR, stdio: "inherit" });
}
console.log("✓ gmail-send 의존성 준비됨");

// 3) 자작 서버 인증 (토큰 없을 때만)
if (existsSync(TOKEN)) {
  console.log("✓ 자작 서버 토큰 이미 있음 (인증 건너뜀)");
} else {
  console.log("• 자작 서버 인증 — 브라우저가 열립니다…");
  try {
    execFileSync("node", ["auth.mjs"], {
      cwd: GMAIL_DIR,
      env: { ...process.env, GMAIL_OAUTH_CLIENT_ID: clientId, GMAIL_OAUTH_CLIENT_SECRET: clientSecret },
      stdio: "inherit",
    });
  } catch {
    console.error("✗ 자작 서버 인증 실패. 포트 3118 점유 시:  lsof -ti:3118 | xargs kill  후 재실행.");
    process.exit(1);
  }
}

console.log("\n남은 1단계 (Pi 안에서):");
console.log("  /mcp-auth gmail            # 공식 서버 인증 (브라우저, 1회)");
console.log("  /mcp reconnect gmail gmail-send");
console.log("\n셋업 완료 ✅");
